#!/bin/sh
# This script wraps the acme certbot into a simple script

TARGET_USER="yourusername"
# Check if script is running as root
if [ "$(id -u)" -eq 0 ]; then
    echo "Running as root, switching to $TARGET_USER..."
    exec sudo -u "$TARGET_USER" -- "$0" "$@"
fi
echo "Running as $USER"

if [ -z "$CERTBOT_EMAIL" ]; then
    echo "Error: CERTBOT_EMAIL is not set or empty" >&2
    exit 1
fi

if [ -z "$CERTBOT_DOMAIN" ]; then
    echo "Error: CERTBOT_DOMAIN is not set or empty" >&2
    exit 1
fi

VAULT="${HOME}/vault"
if [ -n "$CERTBOT_VAULT" ]; then
    VAULT="$CERTBOT_VAULT"
fi

MODE="TEST"
# Check if "--production" is provided as a CLI argument
if [ "$1" -eq "--production" ]; then
    MODE="PRODUCTION"
fi

VERB=$(basename "$0")

CONFIG_DIR="$VAULT/config"
LOG_DIR="$VAULT/logs"
WORK_DIR="$VAULT/work"

. $HOME/.venv/bin/activate
if [ "$MODE" -eq "PRODUCTION" ]; then
    exec "${HOME}/.venv/bin/certbot" "${VERB}" -v \
    --agree-tos \
    --manual \
    --noninteractive \
    --config-dir="${CONFIG_DIR}" \
    --logs-dir="${LOG_DIR}" \
    --work-dir="${WORK_DIR}" \
    --email="${CERTBOT_EMAIL}" \
    --manual-auth-hook="${HOME}/.venv/bin/cloudflare" \
    --preferred-challenges=dns \
    -d "*.${CERTBOT_DOMAIN}"
else
    exec "${HOME}/.venv/bin/certbot" "${VERB}" -v \
    --agree-tos \
    --dry-run \
    --manual \
    --noninteractive \
    --test-cert \
    --config-dir="${CONFIG_DIR}" \
    --logs-dir="${LOG_DIR}" \
    --work-dir="${WORK_DIR}" \
    --email="${CERTBOT_EMAIL}" \
    --manual-auth-hook="${HOME}/.venv/bin/cloudflare" \
    --preferred-challenges=dns \
    -d "*.${CERTBOT_DOMAIN}"
fi
deactivate

